### PR TITLE
support for IBC 3.18.0, timezone support, update config.ini template …

### PR DESCRIPTION
**Pull request by gnzsnz**
- support for IBC 3.18.0
- timezone support for IBGateway
- update IBC config.ini template
- add new env variables to support IBC 3.18.0 funcionality

### CODE REVIEW

**Comment by gnzsnz** [comment]
kind remiender

**Review by Awnedion — APPROVED** [review]

**Comment by jussirantala** [comment]
Why not change the dockerfile to use 3.18.0?

**Comment by natehalsey** [comment]
@gnzsnz Surprised this was closed.

**Comment by gnzsnz** [comment]
I have forked and heavily modified this repo.

If you are interested check it here gnzsnz/ib-gateway-docker

**Pull request closed without merging**
